name: photo-tagger
services:
- name: web
  source_dir: /
  github:
    repo: LaunchpadPhillyTech/photo_tagger
    branch: main
  run_command: gunicorn --bind 0.0.0.0:$PORT main:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: GOOGLE_CLIENT_ID
    scope: RUN_TIME
    type: SECRET
  - key: GOOGLE_CLIENT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: GOOGLE_PROJECT_ID
    scope: RUN_TIME
    type: SECRET
  - key: OAUTH_REDIRECT_URI
    scope: RUN_TIME
    type: SECRET
  - key: FLASK_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: PRODUCTION
    scope: RUN_TIME
    value: "true"
  - key: PORT
    scope: RUN_TIME
    value: "8080"
  http_port: 8080
  routes:
  - path: /
  volumes:
  - name: data-volume
    type: VOLUME
    size: 1GB
    mount_path: /app/data
