name: photo-tagger
services:
- name: web
  source_dir: /
  github:
    repo: LaunchpadPhillyTech/photo_tagger
    branch: main
  run_command: gunicorn --worker-class gevent --workers 1 --bind 0.0.0.0:$PORT main:app
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  health_check:
    http_path: /
  envs:
  - key: PORT
    value: "8080"
  - key: FLASK_ENV
    value: "production"
